### ISSUE TITLE
Shape mismatch in graph classification

### ISSUE THREAD

**Issue by chengzhi-leo** [RinneSz/GMAE#2]
Dear authors,

When I try to run the graph classification bashes I encounter the shape mismatch issue:

```
Original Traceback (most recent call last):
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/dss/dsshome1/lxc04/ge32rol2/workdir/GMAE/graph classification/collator.py", line 105, in collator
    attn_biases[idx][1:, 1:][spatial_poses[idx] >= spatial_pos_max] = float('-inf')
IndexError: The shape of the mask [36, 36] at index 0 does not match the shape of the indexed tensor [35, 35] at index 0
```

As suggested in the error, the attn_biases[idx][1:, 1:] is not in the same shape as spatial_poses[idx]. Through I try to fix it myself (by directly drop extra shapes in the spatial_poses), it's still good to ask if you have any suggestions on how to fix it?

BR

**Comment by RinneSz** [comment]
Delete the [1:, 1:] indexing should work.

**Comment by Leooo-Shen** [comment]
Thanks for the reply. After deleting the indexing I got another mismatch error in model.py, namely `graph_attn_bias` is always larger than `spatial_pos_bias `

```
Traceback (most recent call last):
  File "/dss/dsshome1/lxc04/ge32rol2/workdir/GMAE/graph classification/entry.py", line 145, in <module>
    cli_main()
  File "/dss/dsshome1/lxc04/ge32rol2/workdir/GMAE/graph classification/entry.py", line 127, in cli_main
    trainer.fit(model, datamodule=dm)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in _run_train
    self.fit_loop.run()
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 270, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 203, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 87, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 201, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 248, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 358, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1552, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1673, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 216, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 85, in optimizer_step
    closure_result = closure()
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 146, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 132, in closure
    step_output = self._step_fn()
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 407, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 358, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/workdir/GMAE/graph classification/model.py", line 233, in training_step
    y_hat, graph_mask = self(batched_data, mask)
  File "/dss/dsshome1/lxc04/ge32rol2/miniconda3/envs/gh/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dss/dsshome1/lxc04/ge32rol2/workdir/GMAE/graph classification/model.py", line 195, in forward
    graph_node_feature, graph_attn_bias = self.compute_pos_embeddings(batched_data)
  File "/dss/dsshome1/lxc04/ge32rol2/workdir/GMAE/graph classification/model.py", line 116, in compute_pos_embeddings
    graph_attn_bias = graph_attn_bias + spatial_pos_bias
RuntimeError: The size of tensor a (36) must match the size of tensor b (35) at non-singleton dimension 3
```

**Comment by chengzhi-leo** [comment]
Thanks for the reply. After deleting the indexing I got another mismatching error in model.py.`graph_attn_bias` is always larger than  `spatial_pos_bias `

```
File "/dss/dsshome1/lxc04/ge32rol2/workdir/GMAE/graph classification/model.py", line 195, in forward
  graph_node_feature, graph_attn_bias = self.compute_pos_embeddings(batched_data)
File "/dss/dsshome1/lxc04/ge32rol2/workdir/GMAE/graph classification/model.py", line 116, in compute_pos_embeddings
  graph_attn_bias = graph_attn_bias + spatial_pos_bias
RuntimeError: The size of tensor a (36) must match the size of tensor b (35) at non-singleton dimension 3
```

**Comment by RinneSz** [comment]
I have updated collator.py and this bug should be fixed. The code should be running smoothly now. Please tell me if you encounter any other problems when running the code. Thanks.

**Comment by chengzhi-leo** [comment]
It works, many thanks for the quick fix!
